# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

use_frameworks!

target "SCFacebook" do
  	pod 'SDWebImage'
  	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
end

