# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "SCFacebook" do
  pod 'SDWebImage'
  pod 'SCFacebook', :git => 'https://github.com/lucascorrea/SCFacebook.git', :branch => 'facebook4.0'
end

